name: AIAP Assessment 22
on: [push, workflow_dispatch]

jobs:
  run-end-to-end-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run executable bash script
        run: bash ./run.sh
      - name: Assessment 22 Reminder
        run: |
          echo "Reminder to add AISG-AIAP as a collaborator in your repository"
          echo "Once your submission is complete, fill up the form provided in the Assessment 22 document"
